//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBikesSystem.DataModel.Purchasing
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    internal partial class eBikeEntitiesPurchasing : DbContext
    {
        public eBikeEntitiesPurchasing()
            : base("name=eBikeEntitiesPurchasing")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Employee> Employees { get; set; }
        public DbSet<IDGenerator> IDGenerators { get; set; }
        public DbSet<OrderDetail> OrderDetails { get; set; }
        public DbSet<Order> Orders { get; set; }
        public DbSet<PartCategory> PartCategories { get; set; }
        public DbSet<Part> Parts { get; set; }
        public DbSet<PositionCode> PositionCodes { get; set; }
    
        public virtual ObjectResult<Part> LookupPartforOrderingbyPartnumber(Nullable<int> partnumber)
        {
            var partnumberParameter = partnumber.HasValue ?
                new ObjectParameter("partnumber", partnumber) :
                new ObjectParameter("partnumber", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Part>("LookupPartforOrderingbyPartnumber", partnumberParameter);
        }
    
        public virtual ObjectResult<Part> LookupPartforOrderingbyPartnumber(Nullable<int> partnumber, MergeOption mergeOption)
        {
            var partnumberParameter = partnumber.HasValue ?
                new ObjectParameter("partnumber", partnumber) :
                new ObjectParameter("partnumber", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Part>("LookupPartforOrderingbyPartnumber", mergeOption, partnumberParameter);
        }
    
        public virtual ObjectResult<Part> GetSuggestedOrderList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Part>("GetSuggestedOrderList");
        }
    
        public virtual ObjectResult<Part> GetSuggestedOrderList(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Part>("GetSuggestedOrderList", mergeOption);
        }
    
        public virtual ObjectResult<Part> GetPartbyPartNumber(Nullable<int> partnumber)
        {
            var partnumberParameter = partnumber.HasValue ?
                new ObjectParameter("partnumber", partnumber) :
                new ObjectParameter("partnumber", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Part>("GetPartbyPartNumber", partnumberParameter);
        }
    
        public virtual ObjectResult<Part> GetPartbyPartNumber(Nullable<int> partnumber, MergeOption mergeOption)
        {
            var partnumberParameter = partnumber.HasValue ?
                new ObjectParameter("partnumber", partnumber) :
                new ObjectParameter("partnumber", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Part>("GetPartbyPartNumber", mergeOption, partnumberParameter);
        }
    }
}
