//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBikesSystem.DataModel.Purchasing
{
    using System;
    using System.Collections.Generic;
    
    public partial class IDGenerator
    {
        public string KeyField { get; set; }
        public int LastValue { get; set; }
    }
}
