//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBikesSystem.DataModel.Purchasing
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int OrderNumber { get; set; }
        public int PartNumber { get; set; }
        public int Quantity { get; set; }
        public decimal PurchasePrice { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Part Part { get; set; }
    }
}
