//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBikesSystem.DataModel.Sale
{
    using System;
    using System.Collections.Generic;
    
    public partial class ByPayment
    {
        public ByPayment()
        {
            this.Sales = new HashSet<Sale>();
        }
    
        public int ByPaymentNumber { get; set; }
        public int PaymentTypeCode { get; set; }
        public string CardNumber { get; set; }
    
        public virtual PaymentType PaymentType { get; set; }
        public virtual ICollection<Sale> Sales { get; set; }
    }
}
