//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBikesSystem.DataModel.Sale
{
    using System;
    using System.Collections.Generic;
    
    public partial class Part
    {
        public Part()
        {
            this.SaleDetails = new HashSet<SaleDetail>();
            this.SaleReturnDetails = new HashSet<SaleReturnDetail>();
        }
    
        public int PartNumber { get; set; }
        public string Description { get; set; }
        public decimal PurchasePrice { get; set; }
        public decimal SellingPrice { get; set; }
        public int InStock { get; set; }
        public int ReorderLevel { get; set; }
        public string CategoryType { get; set; }
        public string Refundable { get; set; }
    
        public virtual PartCategory PartCategory { get; set; }
        public virtual ICollection<SaleDetail> SaleDetails { get; set; }
        public virtual ICollection<SaleReturnDetail> SaleReturnDetails { get; set; }
    }
}
