//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBikesSystem.DataModel.Sale
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentType
    {
        public PaymentType()
        {
            this.ByPayments = new HashSet<ByPayment>();
        }
    
        public int PaymentTypeCode { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<ByPayment> ByPayments { get; set; }
    }
}
