//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBikesSystem.DataModel.Sale
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public Sale()
        {
            this.SaleDetails = new HashSet<SaleDetail>();
            this.SaleReturns = new HashSet<SaleReturn>();
        }
    
        public int SaleNumber { get; set; }
        public System.DateTime SaleDate { get; set; }
        public int ByPaymentNumber { get; set; }
        public int EmployeeNumber { get; set; }
        public decimal GST { get; set; }
        public decimal Total { get; set; }
    
        public virtual ByPayment ByPayment { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual ICollection<SaleDetail> SaleDetails { get; set; }
        public virtual ICollection<SaleReturn> SaleReturns { get; set; }
    }
}
