//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBikesSystem.DataModel.Sale
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleDetail
    {
        public int SaleNumber { get; set; }
        public int PartNumber { get; set; }
        public int Quantity { get; set; }
        public decimal SellingPrice { get; set; }
    
        public virtual Part Part { get; set; }
        public virtual Sale Sale { get; set; }
    }
}
